{
  "comments": [
    {
      "key": {
        "uuid": "OWih8a2Y",
        "filename": "contrib/trivial_rebase.py",
        "patchSetId": 3
      },
      "lineNbr": 172,
      "author": {
        "id": 1003873
      },
      "writtenOn": "2013-01-16T12:55:45Z",
      "side": 1,
      "message": "would it help if the error message tells for which of these two commits the GetPatchId failed?",
      "revId": "700981fb8bb7b106d8b5a806291263549a7ac33e",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}