{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "f98b3f0d_8b4fa0db",
        "filename": "java/com/google/gerrit/acceptance/AbstractDaemonTest.java",
        "patchSetId": 3
      },
      "lineNbr": 830,
      "author": {
        "id": 1003935
      },
      "writtenOn": "2020-12-17T13:43:33Z",
      "side": 1,
      "message": "Should this only catch ResourceNotFoundException?\n\nAs it is now the method would also return false if the branch exists but isn\u0027t visible, which is surprising given the method name.",
      "range": {
        "startLine": 830,
        "startChar": 13,
        "endLine": 830,
        "endChar": 29
      },
      "revId": "be4f50155ed99d006ec01e1e2e5ab37177f27c62",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "8ec342c9_dca31aab",
        "filename": "java/com/google/gerrit/acceptance/AbstractDaemonTest.java",
        "patchSetId": 3
      },
      "lineNbr": 830,
      "author": {
        "id": 1091982
      },
      "writtenOn": "2020-12-17T14:12:13Z",
      "side": 1,
      "message": "I will still need to catch RestApiException instead of the more specific ResourceNotFoundException for the code to compile. I can check if the thrown exception class is instance of ResourceNotFoundException though, but I don\u0027t think it\u0027s needed. I\u0027m assuming that failures to get the branch info imply the branch is not visible or doesn\u0027t exist. Please LMK if I need to adjust that.\n\nI agree on renaming the method. Done.",
      "parentUuid": "f98b3f0d_8b4fa0db",
      "range": {
        "startLine": 830,
        "startChar": 13,
        "endLine": 830,
        "endChar": 29
      },
      "revId": "be4f50155ed99d006ec01e1e2e5ab37177f27c62",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ee2c3085_5a09461b",
        "filename": "java/com/google/gerrit/acceptance/AbstractDaemonTest.java",
        "patchSetId": 3
      },
      "lineNbr": 830,
      "author": {
        "id": 1003935
      },
      "writtenOn": "2020-12-17T14:15:10Z",
      "side": 1,
      "message": "\u003e I will still need to catch RestApiException instead of the more specific \n\u003e ResourceNotFoundException for the code to compile.\n\nWhy? Couldn\u0027t you just add \"throws RestApiException\" to the method signature?",
      "parentUuid": "8ec342c9_dca31aab",
      "range": {
        "startLine": 830,
        "startChar": 13,
        "endLine": 830,
        "endChar": 29
      },
      "revId": "be4f50155ed99d006ec01e1e2e5ab37177f27c62",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "663deb07_ed1430eb",
        "filename": "java/com/google/gerrit/acceptance/AbstractDaemonTest.java",
        "patchSetId": 3
      },
      "lineNbr": 830,
      "author": {
        "id": 1091982
      },
      "writtenOn": "2020-12-17T14:25:05Z",
      "side": 1,
      "message": "Did you mean:\n```\nprotected boolean branchExists(BranchNameKey branch) throws RestApiException {\ngApi.projects().name(branch.project().get()).branch(branch.branch()).get();\nreturn true;\n}\n```\n?\n\nBut then I\u0027ll need to handle that exception at the caller (will catch RestApiException as well). I would liked to use this method to check for the branch existence, then create it if it doesn\u0027t exist.\n\nUpdate: I did run the test again and figured out I don\u0027t need this method anymore (because I moved ref/meta/config to another test). I can get rid of this method.",
      "parentUuid": "ee2c3085_5a09461b",
      "range": {
        "startLine": 830,
        "startChar": 13,
        "endLine": 830,
        "endChar": 29
      },
      "revId": "be4f50155ed99d006ec01e1e2e5ab37177f27c62",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0d0bf6f3_30f0f4e0",
        "filename": "java/com/google/gerrit/acceptance/AbstractDaemonTest.java",
        "patchSetId": 3
      },
      "lineNbr": 830,
      "author": {
        "id": 1003935
      },
      "writtenOn": "2020-12-17T14:28:22Z",
      "side": 1,
      "message": "I meant:\n\n  protected boolean branchExistsAndVisible(BranchNameKey branch) throws RestApiException {\n    try {\n      gApi.projects().name(branch.project().get()).branch(branch.branch()).get();\n    } catch (ResourceNotFoundException e) {\n      return false;\n    }\n    return true;\n  }\n\n\u003e But then I\u0027ll need to handle that exception at the caller \n\nNo need to handle to it there, since test methods can have \u0027throws Exception\u0027\u0027\r\n\n\u003e Update: I did run the test again and figured out I don\u0027t need this method anymore\n\u003e (because I moved ref/meta/config to another test). I can get rid of this method.\n\nIf we don\u0027t need this method, even better :)",
      "parentUuid": "663deb07_ed1430eb",
      "range": {
        "startLine": 830,
        "startChar": 13,
        "endLine": 830,
        "endChar": 29
      },
      "revId": "be4f50155ed99d006ec01e1e2e5ab37177f27c62",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}