{
  "comments": [
    {
      "key": {
        "uuid": "5d9595bb_5b082338",
        "filename": "tools/download_file.py",
        "patchSetId": 1
      },
      "lineNbr": 131,
      "author": {
        "id": 1011842
      },
      "writtenOn": "2013-06-13T15:11:03Z",
      "side": 1,
      "message": "Would be clearer with this \"print\" hoisted out of the try block.",
      "revId": "f8b0abd55200b044dc127ff8b6209b40fa0f3238",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "eaf59d3d_3ff32726",
        "filename": "tools/download_file.py",
        "patchSetId": 1
      },
      "lineNbr": 134,
      "author": {
        "id": 1011123
      },
      "writtenOn": "2013-06-13T15:17:12Z",
      "side": 1,
      "message": "s/could/Could\n\nAnd it might be better to put the error on a new line rather than inside quotes.",
      "revId": "f8b0abd55200b044dc127ff8b6209b40fa0f3238",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}